version: '3.8'

services:
  redis-server:
    image: redis
    restart: unless-stopped

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres

  backend:
    build: ./server/
    environment:
      - REDIS_HOST=redis-server
      - POSTGRES_HOST=db

  client:
    build: ./front/
    environment:
      - REACT_APP_BACKEND_URL=http://localhost/api

  proxy:
    image: nginx
    volumes:
      - ./config/:/etc/nginx/
    ports:
      - 80:80
