version: '3.8'

services:
  frontend:
    build: https://github.com/docker-hy/ml-kurkkumopo-frontend.git
    ports:
     - 3000:3000
  server:
    build: https://github.com/docker-hy/ml-kurkkumopo-backend.git
    ports:
     - 5000:5000
    volumes:
      - model:/src/model
  training:
    build: https://github.com/docker-hy/ml-kurkkumopo-training.git
    volumes:
      - model:/src/model
      - files:/src/imgs

volumes:
  model:
  files: